version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: daily_anki_postgres
    restart: always
    ports:
      - "5442:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: technical_exam
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
